title: ie-course
description: Extraction d’information — Reconnaissance et liaison d’entités nommées
url: "https://emanuelaboros.github.io"
baseurl: "/ie-course"
theme: jekyll-theme-primer
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
exclude:
  - Gemfile
  - Gemfile.lock
  - 3-Group-Projects
  - 4-Practical/01-ner-nel-practical.ipynb
